social:
    facebook:
        url: 'https://www.facebook.com/'
        icon:
            inner: fa-facebook-f

    twitter:
        url: 'https://twitter.com/'
        icon:
            inner: fa-twitter

    googleplus:
        url: 'https://plus.google.com/'
        icon:
            inner: fa-google-plus

    youtube:
        url: 'https://www.youtube.com/'
        icon:
            inner: fa-youtube

    pinterest:
        url: 'https://www.pinterest.com/'
        icon:
            inner: fa-pinterest-p
    instagram:
        url: 'https://www.instagram.com'
        icon:
            inner: fa-instagram

    tripadvisor:
        url: 'https://www.tripadvisor.com'
        icon:
            inner: fa-tripadvisor

    blog:
        url: '/blog/'
        icon:
            inner: fa-rss

company:
    name: Fifth Gear Marketing
    address:
        street: Street
        province: Province
        country: Country
phone:
    toll: 888.000.0000
    reception: 250.000.0000
email:
    info: info@fifthgeardev.com
settings:
    header:
        logo:
            url:
    slideshow:
        home:
            template: 'slideshow-home'
        logo:
            url:
            alt: Logo
    page:
        grid:
            left: col-sm-12


    footer:
        grid:
            left:  col-lg-6 col-lg-push-6
            right: col-lg-6 col-lg-pull-6
        logo:
            url:
            alt:
        social:
            enable: true


    copyright:
        grid:
            left:  col-lg-6 col-lg-push-6
            right: col-lg-6 col-lg-pull-6
        text: ', Fifth Gear Marketing'
        year: 2017
    modal:
        logo:

postid:
    terms: 2
    privacy: 2
    contactmodal: 2

forms:
    footer:
        id: 4

slideshow:
    location: afternav
